apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-gp2
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
parameters:
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
mountOptions:
  - debug
