apiVersion: v1
kind: Service
metadata:
  labels:
    koli-app: gitstep
  name: git-api
  namespace: koli-system
spec:
  ports:
  - name: git-api
    port: 8001
    protocol: TCP
    targetPort: 8001
  - name: monitoring
    port: 20251
    protocol: TCP
    targetPort: 20251
  selector:
    koli-app: gitstep
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    koli-app: gitstep
  name: gitstep
  namespace: koli-system
spec:
  replicas: 1
  selector:
    matchLabels:
      koli-app: gitstep
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        koli-app: gitstep
    spec:
      containers:
      - args:
        - --platform-pub-key=/etc/pki/generic/public/auth0.crt
        - --auth0-audience=https://koli.auth0.com/api/v2/
        - --auth0-id=$(NON_INTERACTIVE_CLIENT_ID)
        - --auth0-secret=$(NON_INTERACTIVE_CLIENT_SECRET)
        - --platform-secret=$(PLATFORM_SECRET)
        - --gitapi-host=http://gitapi.kolihub.io
        - --git-home=/home/git
        - --logtostderr
        - --v=4
        - --tls-insecure
        command:
        - gitapi
        image: quay.io/koli/gitstep:development
        env:
        - name: PLATFORM_SECRET
          valueFrom:
            secretKeyRef:
              name: auth0
              key: 'spa-secret.key'
        - name: NON_INTERACTIVE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth0
              key: 'ni-secret.key'
        - name: NON_INTERACTIVE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: auth0
              key: 'ni-client-id.key'
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 20251
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        name: git-api
        ports:
        - containerPort: 8001
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/pki/generic/public
          name: auth0
        - mountPath: /home/git
          name: git-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: auth0
        secret:
          defaultMode: 420
          secretName: auth0
      - name: git-storage
        persistentVolumeClaim:
          claimName: efs-gitstep
