apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: daily-usage-track
  namespace: koli-system
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 60
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - --prometheus-url=http://prometheus-operated.monitoring:9090/api/v1
            - --broker-url=http://broker.koli-system/v1alpha1
            - --broker-secret=/etc/pki/generic/public/spa-secret.key
            command:
            - /usr/bin/python
            - /usr/local/bin/koli-track.py
            image: quay.io/koli/billing:v0.0.1
            imagePullPolicy: Always
            name: koli-billing
            volumeMounts:
            - mountPath: /etc/pki/generic/public
              name: auth0
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          volumes:
          - name: auth0
            secret:
              defaultMode: 420
              secretName: auth0
  schedule: 0 1 * * *
  successfulJobsHistoryLimit: 60
  suspend: false