apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: kube-prom
  name: kong-ingress
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: monitoring
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - koli-system
  selector:
    matchLabels:
      koli-app: kong-ingress
